barkServer: 'https://api.day.app/token'
emailConfigs:
  - user: 'xxxx@gmail.com'
    password: 'xxxxxxxx'
    host: 'imap.gmail.com'
    port: 993
    tls: true
  # Add more email configurations as needed